### ISSUE TITLE
Fails to compute lookahead point

### ISSUE THREAD

**Issue by djud** [leggedrobotics/se2_navigation#3]
I noticed that the computation of the lookahead point fails, if the waypoints are too far spread out. Introducing intermediate points mitigates the problem. 

Below are two images to illustrate the problem. They contain the illustrations as provided by this package (path waypoints in green, lookahead/anchor point in yellow and the robot state as a yellow arrow).

The error message for the failure case is:

[ INFO] [1600849981.064074339, 10.961000000]: [ExcavationStateMachine::run] Excavation state: driving
Going to driving state (received plan)
AckermannSteeringController: Failed to compute lookahead point.
[ERROR] [1600849981.064469624, 10.961000000]: [PurePursuitController::run] Failed to advance path tracker.

![Fail](https://user-images.githubusercontent.com/4202711/93988103-a131da80-fd88-11ea-996c-70123f4219ff.png)

![Success](https://user-images.githubusercontent.com/4202711/93988179-b60e6e00-fd88-11ea-8bc4-e554b00d1799.png)

**Comment by jelavice** [comment]
@djud Thanks for pointing this out. This [PR](https://github.com/leggedrobotics/se2_navigation/pull/4) should address the issue. Could you please verify that it indeed fixes the problem? Thanks, E.

**Comment by djud** [comment]
@jelavice Yes, this fixes the problem when the waypoints are sparse.
